config/routes.rb
ToDo::Application.routes.draw do
  resources :items

  # Allows parameters to be passed to the controller action
  match 'items/complete' => 'items#complete', :via => :post

  # Making the index root at /localhost:3000 
   root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :description, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.where(completed: false) # This only displays the incomplete items
    @new_item = Item.new
    render 'index'
  end

  def complete
    unless params[:item_checkbox]
      flash[:notice] = "Nice try. You didn't check anything off your list."
    else 
      params[:item_checkbox].each do |check|
        item_id = check
        i = Item.find_by_id(item_id)
        i.completed =  true
        i.save
      end
    end
    redirect_to :action => 'index'
  end

  def create
    @new_item = Item.new(item_params)

    # Provide feedback to the user if it's an invalid Items
    unless @new_item.save
      flash[:notice] = "Rut-ro Shaggy. Can't add a blank To-do item." 
    end

    redirect_to action: 'index'
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :completed, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
	    case level
	        when :notice then "alert alert-info"
	        when :success then "alert alert-success"
	        when :error then "alert alert-error"
	        when :alert then "alert alert-error"
	    end
	  end
	  	
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%- model_class = Item -%> <!-- Helper used for the title of the page and creating the table -->
<div class="page-header">
  <h1><%=t '.title', :default => "Ryan's To-do " + model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_for @new_item, url: { action: "create" } do |f| %>  
  <%= f.label "Description" %>
  <%= f.text_field :description %>
  <%= f.label "Priority" %>
  <%= f.check_box :priority %>
  <%= f.submit "Add Item", class: 'btn-mini btn-primary' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:completed) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag items_complete_path, :method => :post do %>
      <% @items.each do |i| %>
        <tr>
          <td><%= check_box_tag "item_checkbox[]", i.id %></td>
          <td><%= i.description %></td>
          <td><%=  "!" if i.priority %></td>
          <td><%=l i.created_at %></td>
          <td>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        item_path(i),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %> <!-- End of items loop -->
  </tbody>
</table>
    <%= submit_tag "Complete To-do's", :class => "btn btn-success" %> <!-- This sends the "item_checkbox" array populated with item id's of those that were checked to the completed action of the items_controller -->
    <% end %> <!-- End of form_tag -->

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js type="text/javascript"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= render 'layouts/shim'%>
</head>
<body>
<div class="container">
  <% if flash[:notice] %>
  	<p class="notice"><%= notice %></p>
  <% end %>

  <% if flash[:alert] %>
  	<p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>
</body>
</html>